// ── IMPOSTOR - Banco de Palavras ──
// 300 palavras organizadas por categoria, cada uma com 3 dicas

const wordBank = [
  // ══ FRUTAS (15) ══
  { word: "Banana", hints: ["É uma fruta", "É amarela", "Macaco gosta"] },
  { word: "Maçã", hints: ["É uma fruta", "Pode ser verde ou vermelha", "Eva ofereceu no paraíso"] },
  { word: "Laranja", hints: ["É uma fruta", "Também é uma cor", "Faz suco popular no café da manhã"] },
  { word: "Morango", hints: ["É uma fruta", "É vermelha com sementinhas", "Combina com chocolate"] },
  { word: "Uva", hints: ["É uma fruta", "Usada para fazer vinho", "Pode ser verde ou roxa"] },
  { word: "Melancia", hints: ["É uma fruta", "É grande e verde por fora", "É vermelha por dentro"] },
  { word: "Abacaxi", hints: ["É uma fruta", "Tem coroa", "É tropical e ácida"] },
  { word: "Manga", hints: ["É uma fruta", "É tropical", "Tem caroço grande"] },
  { word: "Limão", hints: ["É uma fruta", "É azedo", "Faz caipirinha"] },
  { word: "Coco", hints: ["É uma fruta", "Tem casca dura", "Tem água dentro"] },
  { word: "Pêssego", hints: ["É uma fruta", "Tem pelinho na casca", "É alaranjado"] },
  { word: "Abacate", hints: ["É uma fruta", "É verde por dentro", "Faz guacamole"] },
  { word: "Goiaba", hints: ["É uma fruta", "Pode ser vermelha ou branca por dentro", "Faz goiabada"] },
  { word: "Kiwi", hints: ["É uma fruta", "É peludo por fora", "É verde por dentro"] },
  { word: "Cereja", hints: ["É uma fruta", "É pequena e vermelha", "Vai em cima do sorvete"] },

  // ══ ANIMAIS (25) ══
  { word: "Cachorro", hints: ["É um animal", "É o melhor amigo do homem", "Late"] },
  { word: "Gato", hints: ["É um animal", "Tem 7 vidas", "Mia"] },
  { word: "Elefante", hints: ["É um animal", "É o maior terrestre", "Tem tromba"] },
  { word: "Leão", hints: ["É um animal", "É o rei da selva", "Tem juba"] },
  { word: "Girafa", hints: ["É um animal", "Tem pescoço longo", "É o mais alto"] },
  { word: "Macaco", hints: ["É um animal", "Gosta de banana", "Parecido com humano"] },
  { word: "Cobra", hints: ["É um animal", "Não tem patas", "Rasteja"] },
  { word: "Águia", hints: ["É um animal", "Voa alto", "Tem visão incrível"] },
  { word: "Tubarão", hints: ["É um animal", "Vive no mar", "Tem dentes afiados"] },
  { word: "Golfinho", hints: ["É um animal", "Vive no mar", "É muito inteligente"] },
  { word: "Borboleta", hints: ["É um animal", "Tem asas coloridas", "Era lagarta antes"] },
  { word: "Pinguim", hints: ["É um animal", "Vive no gelo", "Não voa mas nada bem"] },
  { word: "Cavalo", hints: ["É um animal", "Usado para montar", "Relincha"] },
  { word: "Tartaruga", hints: ["É um animal", "É lenta", "Tem casco"] },
  { word: "Papagaio", hints: ["É um animal", "Repete o que falam", "Tem penas coloridas"] },
  { word: "Formiga", hints: ["É um animal", "É muito pequena", "Trabalha em grupo"] },
  { word: "Baleia", hints: ["É um animal", "É o maior do mundo", "Vive no oceano"] },
  { word: "Jacaré", hints: ["É um animal", "É réptil", "Vive na água e na terra"] },
  { word: "Coruja", hints: ["É um animal", "É noturna", "Gira a cabeça quase toda"] },
  { word: "Polvo", hints: ["É um animal", "Tem 8 tentáculos", "Vive no mar"] },
  { word: "Camelo", hints: ["É um animal", "Tem corcova", "Vive no deserto"] },
  { word: "Urso", hints: ["É um animal", "Hiberna no inverno", "Gosta de mel"] },
  { word: "Zebra", hints: ["É um animal", "Tem listras", "Parece cavalo"] },
  { word: "Lobo", hints: ["É um animal", "Uiva para a lua", "Vive em matilha"] },
  { word: "Abelha", hints: ["É um animal", "Faz mel", "Tem ferrão"] },

  // ══ ESPORTES (20) ══
  { word: "Futebol", hints: ["É um esporte", "Joga com os pés", "Tem 11 jogadores"] },
  { word: "Basquete", hints: ["É um esporte", "A cesta fica no alto", "Jogadores são altos"] },
  { word: "Vôlei", hints: ["É um esporte", "Tem rede no meio", "Não pode segurar a bola"] },
  { word: "Tênis", hints: ["É um esporte", "Usa raquete", "Tem Roland Garros"] },
  { word: "Natação", hints: ["É um esporte", "Praticado na água", "Tem vários estilos de nado"] },
  { word: "Surfe", hints: ["É um esporte", "Praticado no mar", "Usa prancha"] },
  { word: "Boxe", hints: ["É um esporte", "Usa luvas", "É luta"] },
  { word: "Ciclismo", hints: ["É um esporte", "Usa bicicleta", "Tem Tour de France"] },
  { word: "Golfe", hints: ["É um esporte", "Usa taco", "Tem 18 buracos"] },
  { word: "Skate", hints: ["É um esporte", "Usa prancha com rodinhas", "Faz manobras"] },
  { word: "Judô", hints: ["É um esporte", "É arte marcial", "Usa quimono"] },
  { word: "Atletismo", hints: ["É um esporte", "Inclui corrida", "Tem nas Olimpíadas"] },
  { word: "Handebol", hints: ["É um esporte", "Joga com as mãos", "Tem gol"] },
  { word: "Rugby", hints: ["É um esporte", "A bola é oval", "Pode carregar a bola"] },
  { word: "Esgrima", hints: ["É um esporte", "Usa espada", "Usa máscara de proteção"] },
  { word: "Karatê", hints: ["É um esporte", "É arte marcial", "Usa faixa colorida"] },
  { word: "Hipismo", hints: ["É um esporte", "Montado em cavalo", "Tem saltos"] },
  { word: "Boliche", hints: ["É um esporte", "Derruba pinos", "Usa bola pesada"] },
  { word: "Patinação", hints: ["É um esporte", "Feito no gelo ou asfalto", "Usa patins"] },
  { word: "Xadrez", hints: ["É um esporte", "É jogo de tabuleiro", "Tem rei e rainha"] },

  // ══ COMIDAS (25) ══
  { word: "Pizza", hints: ["É uma comida", "Veio da Itália", "Tem fatias triangulares"] },
  { word: "Hambúrguer", hints: ["É uma comida", "Tem pão e carne", "Fast food famoso"] },
  { word: "Lasanha", hints: ["É uma comida", "Tem camadas", "Leva massa e molho"] },
  { word: "Sushi", hints: ["É uma comida", "Veio do Japão", "Tem arroz e peixe cru"] },
  { word: "Churrasco", hints: ["É uma comida", "Feito na brasa", "Típico do Brasil"] },
  { word: "Feijoada", hints: ["É uma comida", "Prato típico brasileiro", "Tem feijão preto e carne"] },
  { word: "Macarrão", hints: ["É uma comida", "Massa italiana", "Come com molho"] },
  { word: "Tapioca", hints: ["É uma comida", "Feita de mandioca", "Típica do Nordeste"] },
  { word: "Pastel", hints: ["É uma comida", "É frito", "Tem na feira"] },
  { word: "Coxinha", hints: ["É uma comida", "Tem formato de gota", "Recheada de frango"] },
  { word: "Brigadeiro", hints: ["É uma comida", "É doce", "Feito com chocolate e leite condensado"] },
  { word: "Sorvete", hints: ["É uma comida", "É gelado", "Tem vários sabores"] },
  { word: "Pão de queijo", hints: ["É uma comida", "Típico de Minas", "Feito com polvilho"] },
  { word: "Açaí", hints: ["É uma comida", "Vem da Amazônia", "É roxo e gelado"] },
  { word: "Paella", hints: ["É uma comida", "Veio da Espanha", "Tem arroz e frutos do mar"] },
  { word: "Crepe", hints: ["É uma comida", "Veio da França", "Massa fina e recheada"] },
  { word: "Taco", hints: ["É uma comida", "Veio do México", "Tem tortilha dobrada"] },
  { word: "Croissant", hints: ["É uma comida", "Veio da França", "Tem formato de lua"] },
  { word: "Waffle", hints: ["É uma comida", "Tem quadradinhos", "Come com calda"] },
  { word: "Omelete", hints: ["É uma comida", "Feito de ovos", "Pode ter recheio"] },
  { word: "Risoto", hints: ["É uma comida", "É arroz cremoso", "Veio da Itália"] },
  { word: "Fondue", hints: ["É uma comida", "É derretido", "Pode ser de queijo ou chocolate"] },
  { word: "Pipoca", hints: ["É uma comida", "Estoura no fogo", "Come no cinema"] },
  { word: "Pudim", hints: ["É uma comida", "É sobremesa", "Tem calda de caramelo"] },
  { word: "Empanada", hints: ["É uma comida", "Parecida com pastel", "Popular na Argentina"] },

  // ══ PROFISSÕES (20) ══
  { word: "Médico", hints: ["É uma profissão", "Cuida de doentes", "Usa estetoscópio"] },
  { word: "Professor", hints: ["É uma profissão", "Ensina alunos", "Trabalha na escola"] },
  { word: "Bombeiro", hints: ["É uma profissão", "Apaga incêndios", "Faz resgates"] },
  { word: "Policial", hints: ["É uma profissão", "Mantém a ordem", "Usa farda"] },
  { word: "Piloto", hints: ["É uma profissão", "Dirige avião", "Viaja o mundo"] },
  { word: "Dentista", hints: ["É uma profissão", "Cuida dos dentes", "Usa broca"] },
  { word: "Cozinheiro", hints: ["É uma profissão", "Prepara comida", "Trabalha na cozinha"] },
  { word: "Astronauta", hints: ["É uma profissão", "Vai ao espaço", "Usa traje especial"] },
  { word: "Advogado", hints: ["É uma profissão", "Defende pessoas", "Trabalha com leis"] },
  { word: "Engenheiro", hints: ["É uma profissão", "Projeta construções", "Faz cálculos"] },
  { word: "Veterinário", hints: ["É uma profissão", "Cuida de animais", "É médico de bichos"] },
  { word: "Jornalista", hints: ["É uma profissão", "Escreve notícias", "Trabalha com informação"] },
  { word: "Fotógrafo", hints: ["É uma profissão", "Tira fotos", "Usa câmera"] },
  { word: "Padeiro", hints: ["É uma profissão", "Faz pão", "Acorda cedo"] },
  { word: "Pedreiro", hints: ["É uma profissão", "Constrói casas", "Usa cimento"] },
  { word: "Carteiro", hints: ["É uma profissão", "Entrega cartas", "Vai de casa em casa"] },
  { word: "Ator", hints: ["É uma profissão", "Trabalha em filmes", "Interpreta personagens"] },
  { word: "Músico", hints: ["É uma profissão", "Toca instrumento", "Faz shows"] },
  { word: "Pintor", hints: ["É uma profissão", "Usa tinta e pincel", "Cria quadros"] },
  { word: "Cientista", hints: ["É uma profissão", "Faz pesquisas", "Trabalha em laboratório"] },

  // ══ LUGARES (25) ══
  { word: "Praia", hints: ["É um lugar", "Tem areia e mar", "Vai no verão"] },
  { word: "Hospital", hints: ["É um lugar", "Tem médicos", "Vai quando está doente"] },
  { word: "Cinema", hints: ["É um lugar", "Assiste filmes", "Come pipoca"] },
  { word: "Escola", hints: ["É um lugar", "Tem professores", "Lugar de estudar"] },
  { word: "Shopping", hints: ["É um lugar", "Tem muitas lojas", "Vai para comprar"] },
  { word: "Parque", hints: ["É um lugar", "Tem árvores", "Crianças brincam"] },
  { word: "Aeroporto", hints: ["É um lugar", "Tem aviões", "Vai para viajar"] },
  { word: "Biblioteca", hints: ["É um lugar", "Tem muitos livros", "Precisa de silêncio"] },
  { word: "Restaurante", hints: ["É um lugar", "Serve comida", "Tem cardápio"] },
  { word: "Supermercado", hints: ["É um lugar", "Compra comida", "Tem carrinho de compras"] },
  { word: "Farmácia", hints: ["É um lugar", "Vende remédios", "Tem cruz verde"] },
  { word: "Igreja", hints: ["É um lugar", "Lugar de oração", "Tem sino"] },
  { word: "Estádio", hints: ["É um lugar", "Assiste jogos", "Tem torcida"] },
  { word: "Museu", hints: ["É um lugar", "Tem obras de arte", "Aprende história"] },
  { word: "Zoológico", hints: ["É um lugar", "Tem animais", "Leva crianças para ver bichos"] },
  { word: "Padaria", hints: ["É um lugar", "Vende pão", "Tem café da manhã"] },
  { word: "Academia", hints: ["É um lugar", "Faz exercícios", "Tem aparelhos de musculação"] },
  { word: "Banco", hints: ["É um lugar", "Guarda dinheiro", "Tem caixa eletrônico"] },
  { word: "Delegacia", hints: ["É um lugar", "Tem policiais", "Faz boletim de ocorrência"] },
  { word: "Circo", hints: ["É um lugar", "Tem palhaços", "Tem malabaristas"] },
  { word: "Cemitério", hints: ["É um lugar", "Tem túmulos", "Lugar de descanso eterno"] },
  { word: "Posto de gasolina", hints: ["É um lugar", "Abastece carro", "Tem bombas de combustível"] },
  { word: "Salão de beleza", hints: ["É um lugar", "Corta cabelo", "Faz unha"] },
  { word: "Pizzaria", hints: ["É um lugar", "Vende pizza", "Faz delivery"] },
  { word: "Cassino", hints: ["É um lugar", "Joga apostas", "Tem roleta e cartas"] },

  // ══ OBJETOS (30) ══
  { word: "Celular", hints: ["É um objeto", "Todo mundo tem um", "Faz ligações e acessa internet"] },
  { word: "Televisão", hints: ["É um objeto", "Assiste programas", "Tem controle remoto"] },
  { word: "Geladeira", hints: ["É um objeto", "Fica na cozinha", "Mantém comida fria"] },
  { word: "Computador", hints: ["É um objeto", "Tem teclado e mouse", "Usado para trabalhar"] },
  { word: "Relógio", hints: ["É um objeto", "Mostra as horas", "Pode ser de pulso"] },
  { word: "Espelho", hints: ["É um objeto", "Mostra seu reflexo", "Fica no banheiro"] },
  { word: "Guarda-chuva", hints: ["É um objeto", "Protege da chuva", "Abre e fecha"] },
  { word: "Óculos", hints: ["É um objeto", "Ajuda a enxergar", "Fica no rosto"] },
  { word: "Chave", hints: ["É um objeto", "Abre portas", "Carrega no bolso"] },
  { word: "Mochila", hints: ["É um objeto", "Carrega nas costas", "Estudante usa"] },
  { word: "Travesseiro", hints: ["É um objeto", "Coloca a cabeça", "Fica na cama"] },
  { word: "Escova de dente", hints: ["É um objeto", "Limpa os dentes", "Usa pasta junto"] },
  { word: "Tesoura", hints: ["É um objeto", "Corta papel", "Tem duas lâminas"] },
  { word: "Vela", hints: ["É um objeto", "Ilumina com fogo", "Tem no bolo de aniversário"] },
  { word: "Bicicleta", hints: ["É um objeto", "Tem duas rodas", "Pedala para andar"] },
  { word: "Violão", hints: ["É um objeto", "Instrumento musical", "Tem cordas"] },
  { word: "Panela", hints: ["É um objeto", "Cozinha comida", "Fica no fogão"] },
  { word: "Vassoura", hints: ["É um objeto", "Limpa o chão", "Bruxa voa nela"] },
  { word: "Fone de ouvido", hints: ["É um objeto", "Escuta música", "Coloca no ouvido"] },
  { word: "Martelo", hints: ["É um objeto", "Bate pregos", "É ferramenta"] },
  { word: "Caneta", hints: ["É um objeto", "Escreve no papel", "Tem tinta"] },
  { word: "Mala", hints: ["É um objeto", "Carrega roupas", "Usa para viajar"] },
  { word: "Câmera", hints: ["É um objeto", "Tira fotos", "Registra momentos"] },
  { word: "Microfone", hints: ["É um objeto", "Amplifica a voz", "Cantor usa"] },
  { word: "Extintor", hints: ["É um objeto", "Apaga fogo", "É vermelho"] },
  { word: "Bússola", hints: ["É um objeto", "Mostra direção", "Aponta para o norte"] },
  { word: "Binóculo", hints: ["É um objeto", "Vê de longe", "Tem duas lentes"] },
  { word: "Lanterna", hints: ["É um objeto", "Ilumina no escuro", "Usa pilha"] },
  { word: "Dado", hints: ["É um objeto", "Tem 6 lados", "Usado em jogos"] },
  { word: "Apito", hints: ["É um objeto", "Faz barulho agudo", "Juiz de futebol usa"] },

  // ══ PAÍSES (20) ══
  { word: "Brasil", hints: ["É um país", "Fica na América do Sul", "Tem carnaval"] },
  { word: "Japão", hints: ["É um país", "Fica na Ásia", "Tem sushi e samurai"] },
  { word: "Egito", hints: ["É um país", "Tem pirâmides", "Fica na África"] },
  { word: "França", hints: ["É um país", "Tem Torre Eiffel", "Capital é Paris"] },
  { word: "Itália", hints: ["É um país", "Tem pizza e pasta", "Tem a Torre de Pisa"] },
  { word: "China", hints: ["É um país", "Tem muralha famosa", "Maior população do mundo"] },
  { word: "Austrália", hints: ["É um país", "Tem cangurus", "É um continente também"] },
  { word: "México", hints: ["É um país", "Tem tacos", "Faz fronteira com os EUA"] },
  { word: "Índia", hints: ["É um país", "Tem Taj Mahal", "Tem muita especiaria"] },
  { word: "Alemanha", hints: ["É um país", "Tem cerveja famosa", "Capital é Berlim"] },
  { word: "Argentina", hints: ["É um país", "Tem tango", "Vizinho do Brasil"] },
  { word: "Portugal", hints: ["É um país", "Fala português", "Colonizou o Brasil"] },
  { word: "Rússia", hints: ["É um país", "É o maior do mundo", "Tem neve"] },
  { word: "Canadá", hints: ["É um país", "Tem xarope de bordo", "Faz muito frio"] },
  { word: "Grécia", hints: ["É um país", "Berço da democracia", "Tem muitas ilhas"] },
  { word: "Espanha", hints: ["É um país", "Tem touradas", "Capital é Madrid"] },
  { word: "Colômbia", hints: ["É um país", "Famosa pelo café", "Fica na América do Sul"] },
  { word: "Peru", hints: ["É um país", "Tem Machu Picchu", "Fica nos Andes"] },
  { word: "Noruega", hints: ["É um país", "Tem aurora boreal", "Fica na Escandinávia"] },
  { word: "Marrocos", hints: ["É um país", "Fica no norte da África", "Tem deserto do Saara"] },

  // ══ INSTRUMENTOS MUSICAIS (15) ══
  { word: "Piano", hints: ["É um instrumento", "Tem teclas pretas e brancas", "É grande e pesado"] },
  { word: "Guitarra", hints: ["É um instrumento", "Tem cordas", "Usada no rock"] },
  { word: "Bateria", hints: ["É um instrumento", "Bate com baquetas", "Tem pratos e tambores"] },
  { word: "Flauta", hints: ["É um instrumento", "Sopra para tocar", "É fina e longa"] },
  { word: "Saxofone", hints: ["É um instrumento", "Usado no jazz", "É dourado e curvo"] },
  { word: "Trompete", hints: ["É um instrumento", "É de sopro", "Tem som forte"] },
  { word: "Harpa", hints: ["É um instrumento", "Tem muitas cordas", "Anjos tocam no céu"] },
  { word: "Acordeão", hints: ["É um instrumento", "Abre e fecha", "Usado no forró"] },
  { word: "Pandeiro", hints: ["É um instrumento", "Bate com a mão", "Tem platinelas"] },
  { word: "Ukulele", hints: ["É um instrumento", "Parece violão pequeno", "Veio do Havaí"] },
  { word: "Gaita", hints: ["É um instrumento", "Sopra e aspira", "É pequena e cabe no bolso"] },
  { word: "Cavaquinho", hints: ["É um instrumento", "Usado no samba", "Parece violão pequeno"] },
  { word: "Tuba", hints: ["É um instrumento", "É de sopro", "É muito grande"] },
  { word: "Berimbau", hints: ["É um instrumento", "Usado na capoeira", "Tem uma corda só"] },
  { word: "Triângulo", hints: ["É um instrumento", "Tem forma geométrica", "Bate com varinha"] },

  // ══ MEIOS DE TRANSPORTE (15) ══
  { word: "Avião", hints: ["É um transporte", "Voa", "Tem asas"] },
  { word: "Navio", hints: ["É um transporte", "Navega no mar", "É muito grande"] },
  { word: "Trem", hints: ["É um transporte", "Anda nos trilhos", "Apita"] },
  { word: "Helicóptero", hints: ["É um transporte", "Voa", "Tem hélice em cima"] },
  { word: "Submarino", hints: ["É um transporte", "Vai debaixo d'água", "É militar"] },
  { word: "Metrô", hints: ["É um transporte", "Anda debaixo da terra", "Tem nas grandes cidades"] },
  { word: "Moto", hints: ["É um transporte", "Tem duas rodas", "É rápida"] },
  { word: "Ônibus", hints: ["É um transporte", "Leva muitas pessoas", "Tem ponto de parada"] },
  { word: "Ambulância", hints: ["É um transporte", "Leva doentes", "Tem sirene"] },
  { word: "Táxi", hints: ["É um transporte", "É geralmente amarelo", "Paga por corrida"] },
  { word: "Bonde", hints: ["É um transporte", "Anda nos trilhos", "É antigo e elétrico"] },
  { word: "Foguete", hints: ["É um transporte", "Vai ao espaço", "Tem propulsão"] },
  { word: "Canoa", hints: ["É um transporte", "Anda na água", "Rema com remo"] },
  { word: "Patinete", hints: ["É um transporte", "Tem duas rodas", "Empurra com o pé"] },
  { word: "Jangada", hints: ["É um transporte", "Feita de madeira", "Flutua no mar"] },

  // ══ FILMES/PERSONAGENS (20) ══
  { word: "Batman", hints: ["É um personagem", "É super-herói", "Usa capa preta e mora em Gotham"] },
  { word: "Homem-Aranha", hints: ["É um personagem", "Lança teia", "Foi picado por aranha"] },
  { word: "Shrek", hints: ["É um personagem", "É verde", "É um ogro"] },
  { word: "Mickey Mouse", hints: ["É um personagem", "É da Disney", "É um rato"] },
  { word: "Harry Potter", hints: ["É um personagem", "É bruxo", "Tem cicatriz na testa"] },
  { word: "Pikachu", hints: ["É um personagem", "É amarelo", "É um Pokémon elétrico"] },
  { word: "Mario", hints: ["É um personagem", "É encanador", "Pula em cogumelos"] },
  { word: "Nemo", hints: ["É um personagem", "É um peixe", "Foi procurado pelo pai"] },
  { word: "Buzz Lightyear", hints: ["É um personagem", "É astronauta de brinquedo", "Diz ao infinito e além"] },
  { word: "Hulk", hints: ["É um personagem", "É verde e forte", "Fica bravo e cresce"] },
  { word: "Simba", hints: ["É um personagem", "É um leão", "É rei da selva"] },
  { word: "Frozen", hints: ["É um filme", "Tem princesa do gelo", "Tem boneco de neve chamado Olaf"] },
  { word: "Bob Esponja", hints: ["É um personagem", "Mora no fundo do mar", "É uma esponja quadrada"] },
  { word: "Chaves", hints: ["É um personagem", "Mora no barril", "É mexicano"] },
  { word: "Superman", hints: ["É um personagem", "Voa e é forte", "Tem capa vermelha"] },
  { word: "Woody", hints: ["É um personagem", "É um cowboy de brinquedo", "É do Toy Story"] },
  { word: "Dory", hints: ["É um personagem", "É um peixe azul", "Tem memória curta"] },
  { word: "Goku", hints: ["É um personagem", "É de anime", "Fica com cabelo dourado"] },
  { word: "Elsa", hints: ["É um personagem", "Tem poder de gelo", "É princesa"] },
  { word: "Homem de Ferro", hints: ["É um personagem", "Usa armadura", "É bilionário"] },

  // ══ NATUREZA (15) ══
  { word: "Vulcão", hints: ["É da natureza", "Solta lava", "É uma montanha que explode"] },
  { word: "Arco-íris", hints: ["É da natureza", "Tem 7 cores", "Aparece depois da chuva"] },
  { word: "Tsunami", hints: ["É da natureza", "É onda gigante", "É catástrofe no mar"] },
  { word: "Tornado", hints: ["É da natureza", "É vento forte em espiral", "Destrói casas"] },
  { word: "Cachoeira", hints: ["É da natureza", "Água caindo de cima", "Tem em rios e montanhas"] },
  { word: "Deserto", hints: ["É da natureza", "Tem muita areia", "É quente e seco"] },
  { word: "Floresta", hints: ["É da natureza", "Tem muitas árvores", "Amazônia é a maior"] },
  { word: "Oceano", hints: ["É da natureza", "É água salgada", "Cobre a maior parte da Terra"] },
  { word: "Geleira", hints: ["É da natureza", "É gelo gigante", "Está derretendo com aquecimento"] },
  { word: "Montanha", hints: ["É da natureza", "É alta", "Tem neve no topo"] },
  { word: "Caverna", hints: ["É da natureza", "É buraco na rocha", "É escura por dentro"] },
  { word: "Lago", hints: ["É da natureza", "É água parada", "Menor que o mar"] },
  { word: "Relâmpago", hints: ["É da natureza", "É luz no céu", "Vem com trovão"] },
  { word: "Aurora boreal", hints: ["É da natureza", "São luzes coloridas no céu", "Aparece nos polos"] },
  { word: "Eclipse", hints: ["É da natureza", "Sol ou lua ficam escuros", "É fenômeno raro"] },

  // ══ COISAS DO DIA A DIA (20) ══
  { word: "Café", hints: ["É bebida", "Toma de manhã", "Tem cafeína"] },
  { word: "Dinheiro", hints: ["É do dia a dia", "Compra coisas", "Tem notas e moedas"] },
  { word: "Senha", hints: ["É do dia a dia", "Protege sua conta", "Tem letras e números"] },
  { word: "Selfie", hints: ["É do dia a dia", "Foto de si mesmo", "Usa câmera frontal"] },
  { word: "Wi-Fi", hints: ["É do dia a dia", "Internet sem fio", "Todo mundo pergunta a senha"] },
  { word: "Alarme", hints: ["É do dia a dia", "Acorda de manhã", "Faz barulho chato"] },
  { word: "Trânsito", hints: ["É do dia a dia", "Carros parados", "Causa atraso"] },
  { word: "Chuveiro", hints: ["É do dia a dia", "Toma banho com ele", "Sai água quente"] },
  { word: "Elevador", hints: ["É do dia a dia", "Sobe e desce", "Tem em prédios"] },
  { word: "Semáforo", hints: ["É do dia a dia", "Tem 3 cores", "Controla o trânsito"] },
  { word: "Controle remoto", hints: ["É do dia a dia", "Troca de canal", "Sempre some no sofá"] },
  { word: "Escada rolante", hints: ["É do dia a dia", "Sobe sozinha", "Tem no shopping"] },
  { word: "Cartão de crédito", hints: ["É do dia a dia", "Compra sem dinheiro", "Tem fatura no final"] },
  { word: "Impressora", hints: ["É do dia a dia", "Imprime papel", "Sempre falta tinta"] },
  { word: "Ar condicionado", hints: ["É do dia a dia", "Refresca o ambiente", "Usa no calor"] },
  { word: "Carregador", hints: ["É do dia a dia", "Carrega o celular", "Sempre precisa de um"] },
  { word: "Despertador", hints: ["É do dia a dia", "Acorda você", "Faz barulho de manhã"] },
  { word: "Calendário", hints: ["É do dia a dia", "Mostra os dias", "Tem 12 meses"] },
  { word: "Conta de luz", hints: ["É do dia a dia", "Paga todo mês", "Vem pelo correio"] },
  { word: "Máscara", hints: ["É do dia a dia", "Cobre o rosto", "Usou muito na pandemia"] },

  // ══ CORPO HUMANO (15) ══
  { word: "Coração", hints: ["É parte do corpo", "Bombeia sangue", "Símbolo do amor"] },
  { word: "Cérebro", hints: ["É parte do corpo", "Controla tudo", "Fica na cabeça"] },
  { word: "Pulmão", hints: ["É parte do corpo", "Serve para respirar", "Tem dois"] },
  { word: "Estômago", hints: ["É parte do corpo", "Digere comida", "Ronca quando tem fome"] },
  { word: "Olho", hints: ["É parte do corpo", "Serve para enxergar", "Tem pupila e íris"] },
  { word: "Orelha", hints: ["É parte do corpo", "Serve para ouvir", "Tem duas"] },
  { word: "Joelho", hints: ["É parte do corpo", "Dobra a perna", "Fica entre coxa e canela"] },
  { word: "Cotovelo", hints: ["É parte do corpo", "Dobra o braço", "Dói quando bate"] },
  { word: "Língua", hints: ["É parte do corpo", "Sente o gosto", "Fica na boca"] },
  { word: "Dedo", hints: ["É parte do corpo", "Tem nas mãos e pés", "Tem 10 nas mãos"] },
  { word: "Costela", hints: ["É parte do corpo", "Protege os órgãos", "É osso do tórax"] },
  { word: "Coluna", hints: ["É parte do corpo", "Sustenta o corpo", "Fica nas costas"] },
  { word: "Fígado", hints: ["É parte do corpo", "Filtra toxinas", "Fica do lado direito"] },
  { word: "Rim", hints: ["É parte do corpo", "Filtra o sangue", "Tem dois"] },
  { word: "Tornozelo", hints: ["É parte do corpo", "Liga o pé à perna", "Torce fácil"] },

  // ══ MARCAS/EMPRESAS (15) ══
  { word: "Google", hints: ["É uma empresa", "Maior buscador", "Tem logo colorido"] },
  { word: "Nike", hints: ["É uma marca", "Tem o swoosh", "Vende tênis"] },
  { word: "Apple", hints: ["É uma empresa", "Faz iPhone", "Logo é uma maçã mordida"] },
  { word: "Netflix", hints: ["É uma empresa", "Streaming de filmes", "Tem o N vermelho"] },
  { word: "McDonald's", hints: ["É uma empresa", "Tem arcos dourados", "Vende hambúrguer"] },
  { word: "Coca-Cola", hints: ["É uma marca", "É refrigerante", "É vermelha e famosa"] },
  { word: "Instagram", hints: ["É uma empresa", "Rede social de fotos", "Tem stories"] },
  { word: "YouTube", hints: ["É uma empresa", "Plataforma de vídeos", "Tem botão play vermelho"] },
  { word: "WhatsApp", hints: ["É uma empresa", "App de mensagens", "Tem ícone verde"] },
  { word: "Amazon", hints: ["É uma empresa", "Maior loja online", "Tem seta de A até Z"] },
  { word: "Uber", hints: ["É uma empresa", "App de transporte", "Substitui táxi"] },
  { word: "Spotify", hints: ["É uma empresa", "Streaming de música", "Tem ícone verde"] },
  { word: "Ferrari", hints: ["É uma marca", "Faz carros de luxo", "É vermelha e italiana"] },
  { word: "Disney", hints: ["É uma empresa", "Tem parques temáticos", "Criou Mickey Mouse"] },
  { word: "Adidas", hints: ["É uma marca", "Tem 3 listras", "Vende tênis e roupas"] },

  // ══ AÇÕES/VERBOS (20) ══
  { word: "Dormir", hints: ["É uma ação", "Faz de noite", "Fecha os olhos e descansa"] },
  { word: "Cozinhar", hints: ["É uma ação", "Prepara comida", "Usa fogão e panela"] },
  { word: "Dançar", hints: ["É uma ação", "Movimenta o corpo", "Faz com música"] },
  { word: "Nadar", hints: ["É uma ação", "Faz na água", "Move braços e pernas"] },
  { word: "Voar", hints: ["É uma ação", "Pássaros fazem", "Sai do chão"] },
  { word: "Cantar", hints: ["É uma ação", "Usa a voz", "Faz com música"] },
  { word: "Rir", hints: ["É uma ação", "Faz quando acha graça", "É contagioso"] },
  { word: "Chorar", hints: ["É uma ação", "Sai lágrimas", "Faz quando está triste"] },
  { word: "Correr", hints: ["É uma ação", "Move as pernas rápido", "É exercício"] },
  { word: "Pular", hints: ["É uma ação", "Sai do chão", "Crianças adoram"] },
  { word: "Abraçar", hints: ["É uma ação", "Demonstra carinho", "Envolve os braços"] },
  { word: "Assobiar", hints: ["É uma ação", "Faz som com a boca", "Alguns não conseguem"] },
  { word: "Aplaudir", hints: ["É uma ação", "Bate palmas", "Faz no show"] },
  { word: "Rezar", hints: ["É uma ação", "Faz com fé", "Junta as mãos"] },
  { word: "Mentir", hints: ["É uma ação", "Não fala a verdade", "Pinóquio fazia"] },
  { word: "Roncar", hints: ["É uma ação", "Faz dormindo", "Faz barulho à noite"] },
  { word: "Espirrar", hints: ["É uma ação", "É involuntário", "Faz atchim"] },
  { word: "Bocejar", hints: ["É uma ação", "Faz quando tem sono", "É contagioso"] },
  { word: "Mergulhar", hints: ["É uma ação", "Entra na água", "Vai para baixo"] },
  { word: "Escorregar", hints: ["É uma ação", "Perde o equilíbrio", "Pode cair"] },
];

// Export for Node.js (server) and also make available for client
if (typeof module !== 'undefined' && module.exports) {
  module.exports = wordBank;
}
